name: CI
on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - 3.2
          - 3.3
          - 3.4
        gemfile:
          - gemfiles/rails7_1.gemfile
          - gemfiles/rails7_2.gemfile
          - gemfiles/rails8_0.gemfile
          - gemfiles/pinned_dependencies.gemfile
          - Gemfile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install required gems
        run: BUNDLE_GEMFILE=${{ matrix.gemfile }} bundle install --jobs=3 --retry=3
      - name: Run tests
        run: BUNDLE_GEMFILE=${{ matrix.gemfile }} bundle exec rake test
  standard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.2
          bundler-cache: true
      - name: Install required gems
        run: bundle install
      - name: Run standard
        run: bundle exec standardrb
